### ISSUE TITLE
Missing requirement.txt in the repository

### ISSUE THREAD

**Issue by kamzero** [qiuyu96/Carver#3]
Hi,

I wanted to express my appreciation for your work on the project and the open-source mindset behind it. However, I noticed that the repository seems to be missing the requirement.txt file which specifies the project's dependencies. It would be fantastic if you could consider adding this file to the repository.

Thank you for your dedication and contributions to the open-source community.

Best regards,
kamzero

**Comment by qiuyu96** [comment]
Hi, sorry for the absence of the `requirement.txt` file in the repository. I have now added the `requirement.txt` file.

**Comment by kamzero** [comment]
Thanks :D
